### ISSUE TITLE
expires calc wrong in localstorage

### ISSUE THREAD

**Issue by zWingz** [nkoehring/vue-a2b#15]
## key error
![image](https://user-images.githubusercontent.com/13031838/93553185-f777d580-f9a4-11ea-934a-32c4b16835a6.png)

when `setLocalStorage`, the expires will be set to `Date.now` + `30days`, 
but when `getLocalStorage`, it test `Date.now + 30days` > `lastDate.now + 30days`, it equal to cacl `Date.now` > `lastDate.now`, it always true, so it always expired

**Comment by nkoehring** [comment]
Thanks, this is fixed now.
